version: '2'

services:
  bdc:
    build: .
    container_name: bdc
    volumes:
      - ./src/bdc:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8001:8000
    environment:
      - API_PUBLIC_URL=http://localhost:8000
      - API_INTERNAL_URL=http://api:8000
      - DJANGO_DEBUG=True
      - TEST=False
      - NODE_ENV=dev
    networks:
      - mlc_net

networks:
  mlc_net:
    external:
      name: api_mvt_sol_mlc_net
